services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestao_academica_alunos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: desafioaeducacao
    build:
      context: ./backend/Desafio_A+_Educacao/Desafio_A+_Educacao/
    environment:
      ConnectionStrings__PostgreSqlConnection: "Host=postgres;Database=gestao_academica;Username=usuario;Password=senha"
    ports:
      - "8080:80" # Mapeia a porta 80 no contêiner para a porta 8080 na máquina host
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
