services:
  desafio_a_educacao:
    image: ${DOCKER_REGISTRY-}desafioaeducacao
    build:
      context: .
      dockerfile: Desafio_A+_Educacao/Dockerfile
    ports:
    - 5000:5000
    - 5001:5001
  database_edtech:
    image: postgres:latest
    container_name: database_edtech
    environment:
     - POSTGRES_DB=edtech
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/edtech-db:/var/lib/postgresql/data
    ports:  
     - 5432:5432