// <auto-generated />
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio_A__Educacao.Domain.Entities.Student", b =>
                {
                    b.Property<string>("RA")
                        .HasColumnType("text")
                        .HasColumnName("RA");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RA");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            RA = "RA000001",
                            CPF = "12345678901",
                            Email = "student1@example.com",
                            Id = 1,
                            Name = "Student 1"
                        },
                        new
                        {
                            RA = "RA000002",
                            CPF = "12345678902",
                            Email = "student2@example.com",
                            Id = 2,
                            Name = "Student 2"
                        },
                        new
                        {
                            RA = "RA000003",
                            CPF = "12345678903",
                            Email = "student3@example.com",
                            Id = 3,
                            Name = "Student 3"
                        },
                        new
                        {
                            RA = "RA000004",
                            CPF = "12345678904",
                            Email = "student4@example.com",
                            Id = 4,
                            Name = "Student 4"
                        },
                        new
                        {
                            RA = "RA000005",
                            CPF = "12345678905",
                            Email = "student5@example.com",
                            Id = 5,
                            Name = "Student 5"
                        },
                        new
                        {
                            RA = "RA000006",
                            CPF = "12345678906",
                            Email = "student6@example.com",
                            Id = 6,
                            Name = "Student 6"
                        },
                        new
                        {
                            RA = "RA000007",
                            CPF = "12345678907",
                            Email = "student7@example.com",
                            Id = 7,
                            Name = "Student 7"
                        },
                        new
                        {
                            RA = "RA000008",
                            CPF = "12345678908",
                            Email = "student8@example.com",
                            Id = 8,
                            Name = "Student 8"
                        },
                        new
                        {
                            RA = "RA000009",
                            CPF = "12345678909",
                            Email = "student9@example.com",
                            Id = 9,
                            Name = "Student 9"
                        },
                        new
                        {
                            RA = "RA000010",
                            CPF = "12345678910",
                            Email = "student10@example.com",
                            Id = 10,
                            Name = "Student 10"
                        },
                        new
                        {
                            RA = "RA000011",
                            CPF = "12345678911",
                            Email = "student11@example.com",
                            Id = 11,
                            Name = "Student 11"
                        },
                        new
                        {
                            RA = "RA000012",
                            CPF = "12345678912",
                            Email = "student12@example.com",
                            Id = 12,
                            Name = "Student 12"
                        },
                        new
                        {
                            RA = "RA000013",
                            CPF = "12345678913",
                            Email = "student13@example.com",
                            Id = 13,
                            Name = "Student 13"
                        },
                        new
                        {
                            RA = "RA000014",
                            CPF = "12345678914",
                            Email = "student14@example.com",
                            Id = 14,
                            Name = "Student 14"
                        },
                        new
                        {
                            RA = "RA000015",
                            CPF = "12345678915",
                            Email = "student15@example.com",
                            Id = 15,
                            Name = "Student 15"
                        },
                        new
                        {
                            RA = "RA000016",
                            CPF = "12345678916",
                            Email = "student16@example.com",
                            Id = 16,
                            Name = "Student 16"
                        },
                        new
                        {
                            RA = "RA000017",
                            CPF = "12345678917",
                            Email = "student17@example.com",
                            Id = 17,
                            Name = "Student 17"
                        },
                        new
                        {
                            RA = "RA000018",
                            CPF = "12345678918",
                            Email = "student18@example.com",
                            Id = 18,
                            Name = "Student 18"
                        },
                        new
                        {
                            RA = "RA000019",
                            CPF = "12345678919",
                            Email = "student19@example.com",
                            Id = 19,
                            Name = "Student 19"
                        },
                        new
                        {
                            RA = "RA000020",
                            CPF = "12345678920",
                            Email = "student20@example.com",
                            Id = 20,
                            Name = "Student 20"
                        },
                        new
                        {
                            RA = "RA000021",
                            CPF = "12345678921",
                            Email = "student21@example.com",
                            Id = 21,
                            Name = "Student 21"
                        },
                        new
                        {
                            RA = "RA000022",
                            CPF = "12345678922",
                            Email = "student22@example.com",
                            Id = 22,
                            Name = "Student 22"
                        },
                        new
                        {
                            RA = "RA000023",
                            CPF = "12345678923",
                            Email = "student23@example.com",
                            Id = 23,
                            Name = "Student 23"
                        },
                        new
                        {
                            RA = "RA000024",
                            CPF = "12345678924",
                            Email = "student24@example.com",
                            Id = 24,
                            Name = "Student 24"
                        },
                        new
                        {
                            RA = "RA000025",
                            CPF = "12345678925",
                            Email = "student25@example.com",
                            Id = 25,
                            Name = "Student 25"
                        },
                        new
                        {
                            RA = "RA000026",
                            CPF = "12345678926",
                            Email = "student26@example.com",
                            Id = 26,
                            Name = "Student 26"
                        },
                        new
                        {
                            RA = "RA000027",
                            CPF = "12345678927",
                            Email = "student27@example.com",
                            Id = 27,
                            Name = "Student 27"
                        },
                        new
                        {
                            RA = "RA000028",
                            CPF = "12345678928",
                            Email = "student28@example.com",
                            Id = 28,
                            Name = "Student 28"
                        },
                        new
                        {
                            RA = "RA000029",
                            CPF = "12345678929",
                            Email = "student29@example.com",
                            Id = 29,
                            Name = "Student 29"
                        },
                        new
                        {
                            RA = "RA000030",
                            CPF = "12345678930",
                            Email = "student30@example.com",
                            Id = 30,
                            Name = "Student 30"
                        },
                        new
                        {
                            RA = "RA000031",
                            CPF = "12345678931",
                            Email = "student31@example.com",
                            Id = 31,
                            Name = "Student 31"
                        },
                        new
                        {
                            RA = "RA000032",
                            CPF = "12345678932",
                            Email = "student32@example.com",
                            Id = 32,
                            Name = "Student 32"
                        },
                        new
                        {
                            RA = "RA000033",
                            CPF = "12345678933",
                            Email = "student33@example.com",
                            Id = 33,
                            Name = "Student 33"
                        },
                        new
                        {
                            RA = "RA000034",
                            CPF = "12345678934",
                            Email = "student34@example.com",
                            Id = 34,
                            Name = "Student 34"
                        },
                        new
                        {
                            RA = "RA000035",
                            CPF = "12345678935",
                            Email = "student35@example.com",
                            Id = 35,
                            Name = "Student 35"
                        },
                        new
                        {
                            RA = "RA000036",
                            CPF = "12345678936",
                            Email = "student36@example.com",
                            Id = 36,
                            Name = "Student 36"
                        },
                        new
                        {
                            RA = "RA000037",
                            CPF = "12345678937",
                            Email = "student37@example.com",
                            Id = 37,
                            Name = "Student 37"
                        },
                        new
                        {
                            RA = "RA000038",
                            CPF = "12345678938",
                            Email = "student38@example.com",
                            Id = 38,
                            Name = "Student 38"
                        },
                        new
                        {
                            RA = "RA000039",
                            CPF = "12345678939",
                            Email = "student39@example.com",
                            Id = 39,
                            Name = "Student 39"
                        },
                        new
                        {
                            RA = "RA000040",
                            CPF = "12345678940",
                            Email = "student40@example.com",
                            Id = 40,
                            Name = "Student 40"
                        },
                        new
                        {
                            RA = "RA000041",
                            CPF = "12345678941",
                            Email = "student41@example.com",
                            Id = 41,
                            Name = "Student 41"
                        },
                        new
                        {
                            RA = "RA000042",
                            CPF = "12345678942",
                            Email = "student42@example.com",
                            Id = 42,
                            Name = "Student 42"
                        },
                        new
                        {
                            RA = "RA000043",
                            CPF = "12345678943",
                            Email = "student43@example.com",
                            Id = 43,
                            Name = "Student 43"
                        },
                        new
                        {
                            RA = "RA000044",
                            CPF = "12345678944",
                            Email = "student44@example.com",
                            Id = 44,
                            Name = "Student 44"
                        },
                        new
                        {
                            RA = "RA000045",
                            CPF = "12345678945",
                            Email = "student45@example.com",
                            Id = 45,
                            Name = "Student 45"
                        },
                        new
                        {
                            RA = "RA000046",
                            CPF = "12345678946",
                            Email = "student46@example.com",
                            Id = 46,
                            Name = "Student 46"
                        },
                        new
                        {
                            RA = "RA000047",
                            CPF = "12345678947",
                            Email = "student47@example.com",
                            Id = 47,
                            Name = "Student 47"
                        },
                        new
                        {
                            RA = "RA000048",
                            CPF = "12345678948",
                            Email = "student48@example.com",
                            Id = 48,
                            Name = "Student 48"
                        },
                        new
                        {
                            RA = "RA000049",
                            CPF = "12345678949",
                            Email = "student49@example.com",
                            Id = 49,
                            Name = "Student 49"
                        },
                        new
                        {
                            RA = "RA000050",
                            CPF = "12345678950",
                            Email = "student50@example.com",
                            Id = 50,
                            Name = "Student 50"
                        },
                        new
                        {
                            RA = "RA000051",
                            CPF = "12345678951",
                            Email = "student51@example.com",
                            Id = 51,
                            Name = "Student 51"
                        },
                        new
                        {
                            RA = "RA000052",
                            CPF = "12345678952",
                            Email = "student52@example.com",
                            Id = 52,
                            Name = "Student 52"
                        },
                        new
                        {
                            RA = "RA000053",
                            CPF = "12345678953",
                            Email = "student53@example.com",
                            Id = 53,
                            Name = "Student 53"
                        },
                        new
                        {
                            RA = "RA000054",
                            CPF = "12345678954",
                            Email = "student54@example.com",
                            Id = 54,
                            Name = "Student 54"
                        },
                        new
                        {
                            RA = "RA000055",
                            CPF = "12345678955",
                            Email = "student55@example.com",
                            Id = 55,
                            Name = "Student 55"
                        },
                        new
                        {
                            RA = "RA000056",
                            CPF = "12345678956",
                            Email = "student56@example.com",
                            Id = 56,
                            Name = "Student 56"
                        },
                        new
                        {
                            RA = "RA000057",
                            CPF = "12345678957",
                            Email = "student57@example.com",
                            Id = 57,
                            Name = "Student 57"
                        },
                        new
                        {
                            RA = "RA000058",
                            CPF = "12345678958",
                            Email = "student58@example.com",
                            Id = 58,
                            Name = "Student 58"
                        },
                        new
                        {
                            RA = "RA000059",
                            CPF = "12345678959",
                            Email = "student59@example.com",
                            Id = 59,
                            Name = "Student 59"
                        },
                        new
                        {
                            RA = "RA000060",
                            CPF = "12345678960",
                            Email = "student60@example.com",
                            Id = 60,
                            Name = "Student 60"
                        },
                        new
                        {
                            RA = "RA000061",
                            CPF = "12345678961",
                            Email = "student61@example.com",
                            Id = 61,
                            Name = "Student 61"
                        },
                        new
                        {
                            RA = "RA000062",
                            CPF = "12345678962",
                            Email = "student62@example.com",
                            Id = 62,
                            Name = "Student 62"
                        },
                        new
                        {
                            RA = "RA000063",
                            CPF = "12345678963",
                            Email = "student63@example.com",
                            Id = 63,
                            Name = "Student 63"
                        },
                        new
                        {
                            RA = "RA000064",
                            CPF = "12345678964",
                            Email = "student64@example.com",
                            Id = 64,
                            Name = "Student 64"
                        },
                        new
                        {
                            RA = "RA000065",
                            CPF = "12345678965",
                            Email = "student65@example.com",
                            Id = 65,
                            Name = "Student 65"
                        },
                        new
                        {
                            RA = "RA000066",
                            CPF = "12345678966",
                            Email = "student66@example.com",
                            Id = 66,
                            Name = "Student 66"
                        },
                        new
                        {
                            RA = "RA000067",
                            CPF = "12345678967",
                            Email = "student67@example.com",
                            Id = 67,
                            Name = "Student 67"
                        },
                        new
                        {
                            RA = "RA000068",
                            CPF = "12345678968",
                            Email = "student68@example.com",
                            Id = 68,
                            Name = "Student 68"
                        },
                        new
                        {
                            RA = "RA000069",
                            CPF = "12345678969",
                            Email = "student69@example.com",
                            Id = 69,
                            Name = "Student 69"
                        },
                        new
                        {
                            RA = "RA000070",
                            CPF = "12345678970",
                            Email = "student70@example.com",
                            Id = 70,
                            Name = "Student 70"
                        },
                        new
                        {
                            RA = "RA000071",
                            CPF = "12345678971",
                            Email = "student71@example.com",
                            Id = 71,
                            Name = "Student 71"
                        },
                        new
                        {
                            RA = "RA000072",
                            CPF = "12345678972",
                            Email = "student72@example.com",
                            Id = 72,
                            Name = "Student 72"
                        },
                        new
                        {
                            RA = "RA000073",
                            CPF = "12345678973",
                            Email = "student73@example.com",
                            Id = 73,
                            Name = "Student 73"
                        },
                        new
                        {
                            RA = "RA000074",
                            CPF = "12345678974",
                            Email = "student74@example.com",
                            Id = 74,
                            Name = "Student 74"
                        },
                        new
                        {
                            RA = "RA000075",
                            CPF = "12345678975",
                            Email = "student75@example.com",
                            Id = 75,
                            Name = "Student 75"
                        },
                        new
                        {
                            RA = "RA000076",
                            CPF = "12345678976",
                            Email = "student76@example.com",
                            Id = 76,
                            Name = "Student 76"
                        },
                        new
                        {
                            RA = "RA000077",
                            CPF = "12345678977",
                            Email = "student77@example.com",
                            Id = 77,
                            Name = "Student 77"
                        },
                        new
                        {
                            RA = "RA000078",
                            CPF = "12345678978",
                            Email = "student78@example.com",
                            Id = 78,
                            Name = "Student 78"
                        },
                        new
                        {
                            RA = "RA000079",
                            CPF = "12345678979",
                            Email = "student79@example.com",
                            Id = 79,
                            Name = "Student 79"
                        },
                        new
                        {
                            RA = "RA000080",
                            CPF = "12345678980",
                            Email = "student80@example.com",
                            Id = 80,
                            Name = "Student 80"
                        },
                        new
                        {
                            RA = "RA000081",
                            CPF = "12345678981",
                            Email = "student81@example.com",
                            Id = 81,
                            Name = "Student 81"
                        },
                        new
                        {
                            RA = "RA000082",
                            CPF = "12345678982",
                            Email = "student82@example.com",
                            Id = 82,
                            Name = "Student 82"
                        },
                        new
                        {
                            RA = "RA000083",
                            CPF = "12345678983",
                            Email = "student83@example.com",
                            Id = 83,
                            Name = "Student 83"
                        },
                        new
                        {
                            RA = "RA000084",
                            CPF = "12345678984",
                            Email = "student84@example.com",
                            Id = 84,
                            Name = "Student 84"
                        },
                        new
                        {
                            RA = "RA000085",
                            CPF = "12345678985",
                            Email = "student85@example.com",
                            Id = 85,
                            Name = "Student 85"
                        },
                        new
                        {
                            RA = "RA000086",
                            CPF = "12345678986",
                            Email = "student86@example.com",
                            Id = 86,
                            Name = "Student 86"
                        },
                        new
                        {
                            RA = "RA000087",
                            CPF = "12345678987",
                            Email = "student87@example.com",
                            Id = 87,
                            Name = "Student 87"
                        },
                        new
                        {
                            RA = "RA000088",
                            CPF = "12345678988",
                            Email = "student88@example.com",
                            Id = 88,
                            Name = "Student 88"
                        },
                        new
                        {
                            RA = "RA000089",
                            CPF = "12345678989",
                            Email = "student89@example.com",
                            Id = 89,
                            Name = "Student 89"
                        },
                        new
                        {
                            RA = "RA000090",
                            CPF = "12345678990",
                            Email = "student90@example.com",
                            Id = 90,
                            Name = "Student 90"
                        },
                        new
                        {
                            RA = "RA000091",
                            CPF = "12345678991",
                            Email = "student91@example.com",
                            Id = 91,
                            Name = "Student 91"
                        },
                        new
                        {
                            RA = "RA000092",
                            CPF = "12345678992",
                            Email = "student92@example.com",
                            Id = 92,
                            Name = "Student 92"
                        },
                        new
                        {
                            RA = "RA000093",
                            CPF = "12345678993",
                            Email = "student93@example.com",
                            Id = 93,
                            Name = "Student 93"
                        },
                        new
                        {
                            RA = "RA000094",
                            CPF = "12345678994",
                            Email = "student94@example.com",
                            Id = 94,
                            Name = "Student 94"
                        },
                        new
                        {
                            RA = "RA000095",
                            CPF = "12345678995",
                            Email = "student95@example.com",
                            Id = 95,
                            Name = "Student 95"
                        },
                        new
                        {
                            RA = "RA000096",
                            CPF = "12345678996",
                            Email = "student96@example.com",
                            Id = 96,
                            Name = "Student 96"
                        },
                        new
                        {
                            RA = "RA000097",
                            CPF = "12345678997",
                            Email = "student97@example.com",
                            Id = 97,
                            Name = "Student 97"
                        },
                        new
                        {
                            RA = "RA000098",
                            CPF = "12345678998",
                            Email = "student98@example.com",
                            Id = 98,
                            Name = "Student 98"
                        },
                        new
                        {
                            RA = "RA000099",
                            CPF = "12345678999",
                            Email = "student99@example.com",
                            Id = 99,
                            Name = "Student 99"
                        },
                        new
                        {
                            RA = "RA000100",
                            CPF = "123456789100",
                            Email = "student100@example.com",
                            Id = 100,
                            Name = "Student 100"
                        },
                        new
                        {
                            RA = "RA000101",
                            CPF = "123456789101",
                            Email = "student101@example.com",
                            Id = 101,
                            Name = "Student 101"
                        },
                        new
                        {
                            RA = "RA000102",
                            CPF = "123456789102",
                            Email = "student102@example.com",
                            Id = 102,
                            Name = "Student 102"
                        },
                        new
                        {
                            RA = "RA000103",
                            CPF = "123456789103",
                            Email = "student103@example.com",
                            Id = 103,
                            Name = "Student 103"
                        },
                        new
                        {
                            RA = "RA000104",
                            CPF = "123456789104",
                            Email = "student104@example.com",
                            Id = 104,
                            Name = "Student 104"
                        },
                        new
                        {
                            RA = "RA000105",
                            CPF = "123456789105",
                            Email = "student105@example.com",
                            Id = 105,
                            Name = "Student 105"
                        },
                        new
                        {
                            RA = "RA000106",
                            CPF = "123456789106",
                            Email = "student106@example.com",
                            Id = 106,
                            Name = "Student 106"
                        },
                        new
                        {
                            RA = "RA000107",
                            CPF = "123456789107",
                            Email = "student107@example.com",
                            Id = 107,
                            Name = "Student 107"
                        },
                        new
                        {
                            RA = "RA000108",
                            CPF = "123456789108",
                            Email = "student108@example.com",
                            Id = 108,
                            Name = "Student 108"
                        },
                        new
                        {
                            RA = "RA000109",
                            CPF = "123456789109",
                            Email = "student109@example.com",
                            Id = 109,
                            Name = "Student 109"
                        },
                        new
                        {
                            RA = "RA000110",
                            CPF = "123456789110",
                            Email = "student110@example.com",
                            Id = 110,
                            Name = "Student 110"
                        },
                        new
                        {
                            RA = "RA000111",
                            CPF = "123456789111",
                            Email = "student111@example.com",
                            Id = 111,
                            Name = "Student 111"
                        },
                        new
                        {
                            RA = "RA000112",
                            CPF = "123456789112",
                            Email = "student112@example.com",
                            Id = 112,
                            Name = "Student 112"
                        },
                        new
                        {
                            RA = "RA000113",
                            CPF = "123456789113",
                            Email = "student113@example.com",
                            Id = 113,
                            Name = "Student 113"
                        },
                        new
                        {
                            RA = "RA000114",
                            CPF = "123456789114",
                            Email = "student114@example.com",
                            Id = 114,
                            Name = "Student 114"
                        },
                        new
                        {
                            RA = "RA000115",
                            CPF = "123456789115",
                            Email = "student115@example.com",
                            Id = 115,
                            Name = "Student 115"
                        },
                        new
                        {
                            RA = "RA000116",
                            CPF = "123456789116",
                            Email = "student116@example.com",
                            Id = 116,
                            Name = "Student 116"
                        },
                        new
                        {
                            RA = "RA000117",
                            CPF = "123456789117",
                            Email = "student117@example.com",
                            Id = 117,
                            Name = "Student 117"
                        },
                        new
                        {
                            RA = "RA000118",
                            CPF = "123456789118",
                            Email = "student118@example.com",
                            Id = 118,
                            Name = "Student 118"
                        },
                        new
                        {
                            RA = "RA000119",
                            CPF = "123456789119",
                            Email = "student119@example.com",
                            Id = 119,
                            Name = "Student 119"
                        },
                        new
                        {
                            RA = "RA000120",
                            CPF = "123456789120",
                            Email = "student120@example.com",
                            Id = 120,
                            Name = "Student 120"
                        },
                        new
                        {
                            RA = "RA000121",
                            CPF = "123456789121",
                            Email = "student121@example.com",
                            Id = 121,
                            Name = "Student 121"
                        },
                        new
                        {
                            RA = "RA000122",
                            CPF = "123456789122",
                            Email = "student122@example.com",
                            Id = 122,
                            Name = "Student 122"
                        },
                        new
                        {
                            RA = "RA000123",
                            CPF = "123456789123",
                            Email = "student123@example.com",
                            Id = 123,
                            Name = "Student 123"
                        },
                        new
                        {
                            RA = "RA000124",
                            CPF = "123456789124",
                            Email = "student124@example.com",
                            Id = 124,
                            Name = "Student 124"
                        },
                        new
                        {
                            RA = "RA000125",
                            CPF = "123456789125",
                            Email = "student125@example.com",
                            Id = 125,
                            Name = "Student 125"
                        },
                        new
                        {
                            RA = "RA000126",
                            CPF = "123456789126",
                            Email = "student126@example.com",
                            Id = 126,
                            Name = "Student 126"
                        },
                        new
                        {
                            RA = "RA000127",
                            CPF = "123456789127",
                            Email = "student127@example.com",
                            Id = 127,
                            Name = "Student 127"
                        },
                        new
                        {
                            RA = "RA000128",
                            CPF = "123456789128",
                            Email = "student128@example.com",
                            Id = 128,
                            Name = "Student 128"
                        },
                        new
                        {
                            RA = "RA000129",
                            CPF = "123456789129",
                            Email = "student129@example.com",
                            Id = 129,
                            Name = "Student 129"
                        },
                        new
                        {
                            RA = "RA000130",
                            CPF = "123456789130",
                            Email = "student130@example.com",
                            Id = 130,
                            Name = "Student 130"
                        },
                        new
                        {
                            RA = "RA000131",
                            CPF = "123456789131",
                            Email = "student131@example.com",
                            Id = 131,
                            Name = "Student 131"
                        },
                        new
                        {
                            RA = "RA000132",
                            CPF = "123456789132",
                            Email = "student132@example.com",
                            Id = 132,
                            Name = "Student 132"
                        },
                        new
                        {
                            RA = "RA000133",
                            CPF = "123456789133",
                            Email = "student133@example.com",
                            Id = 133,
                            Name = "Student 133"
                        },
                        new
                        {
                            RA = "RA000134",
                            CPF = "123456789134",
                            Email = "student134@example.com",
                            Id = 134,
                            Name = "Student 134"
                        },
                        new
                        {
                            RA = "RA000135",
                            CPF = "123456789135",
                            Email = "student135@example.com",
                            Id = 135,
                            Name = "Student 135"
                        },
                        new
                        {
                            RA = "RA000136",
                            CPF = "123456789136",
                            Email = "student136@example.com",
                            Id = 136,
                            Name = "Student 136"
                        },
                        new
                        {
                            RA = "RA000137",
                            CPF = "123456789137",
                            Email = "student137@example.com",
                            Id = 137,
                            Name = "Student 137"
                        },
                        new
                        {
                            RA = "RA000138",
                            CPF = "123456789138",
                            Email = "student138@example.com",
                            Id = 138,
                            Name = "Student 138"
                        },
                        new
                        {
                            RA = "RA000139",
                            CPF = "123456789139",
                            Email = "student139@example.com",
                            Id = 139,
                            Name = "Student 139"
                        },
                        new
                        {
                            RA = "RA000140",
                            CPF = "123456789140",
                            Email = "student140@example.com",
                            Id = 140,
                            Name = "Student 140"
                        },
                        new
                        {
                            RA = "RA000141",
                            CPF = "123456789141",
                            Email = "student141@example.com",
                            Id = 141,
                            Name = "Student 141"
                        },
                        new
                        {
                            RA = "RA000142",
                            CPF = "123456789142",
                            Email = "student142@example.com",
                            Id = 142,
                            Name = "Student 142"
                        },
                        new
                        {
                            RA = "RA000143",
                            CPF = "123456789143",
                            Email = "student143@example.com",
                            Id = 143,
                            Name = "Student 143"
                        },
                        new
                        {
                            RA = "RA000144",
                            CPF = "123456789144",
                            Email = "student144@example.com",
                            Id = 144,
                            Name = "Student 144"
                        },
                        new
                        {
                            RA = "RA000145",
                            CPF = "123456789145",
                            Email = "student145@example.com",
                            Id = 145,
                            Name = "Student 145"
                        },
                        new
                        {
                            RA = "RA000146",
                            CPF = "123456789146",
                            Email = "student146@example.com",
                            Id = 146,
                            Name = "Student 146"
                        },
                        new
                        {
                            RA = "RA000147",
                            CPF = "123456789147",
                            Email = "student147@example.com",
                            Id = 147,
                            Name = "Student 147"
                        },
                        new
                        {
                            RA = "RA000148",
                            CPF = "123456789148",
                            Email = "student148@example.com",
                            Id = 148,
                            Name = "Student 148"
                        },
                        new
                        {
                            RA = "RA000149",
                            CPF = "123456789149",
                            Email = "student149@example.com",
                            Id = 149,
                            Name = "Student 149"
                        },
                        new
                        {
                            RA = "RA000150",
                            CPF = "123456789150",
                            Email = "student150@example.com",
                            Id = 150,
                            Name = "Student 150"
                        },
                        new
                        {
                            RA = "RA000151",
                            CPF = "123456789151",
                            Email = "student151@example.com",
                            Id = 151,
                            Name = "Student 151"
                        },
                        new
                        {
                            RA = "RA000152",
                            CPF = "123456789152",
                            Email = "student152@example.com",
                            Id = 152,
                            Name = "Student 152"
                        },
                        new
                        {
                            RA = "RA000153",
                            CPF = "123456789153",
                            Email = "student153@example.com",
                            Id = 153,
                            Name = "Student 153"
                        },
                        new
                        {
                            RA = "RA000154",
                            CPF = "123456789154",
                            Email = "student154@example.com",
                            Id = 154,
                            Name = "Student 154"
                        },
                        new
                        {
                            RA = "RA000155",
                            CPF = "123456789155",
                            Email = "student155@example.com",
                            Id = 155,
                            Name = "Student 155"
                        },
                        new
                        {
                            RA = "RA000156",
                            CPF = "123456789156",
                            Email = "student156@example.com",
                            Id = 156,
                            Name = "Student 156"
                        },
                        new
                        {
                            RA = "RA000157",
                            CPF = "123456789157",
                            Email = "student157@example.com",
                            Id = 157,
                            Name = "Student 157"
                        },
                        new
                        {
                            RA = "RA000158",
                            CPF = "123456789158",
                            Email = "student158@example.com",
                            Id = 158,
                            Name = "Student 158"
                        },
                        new
                        {
                            RA = "RA000159",
                            CPF = "123456789159",
                            Email = "student159@example.com",
                            Id = 159,
                            Name = "Student 159"
                        },
                        new
                        {
                            RA = "RA000160",
                            CPF = "123456789160",
                            Email = "student160@example.com",
                            Id = 160,
                            Name = "Student 160"
                        },
                        new
                        {
                            RA = "RA000161",
                            CPF = "123456789161",
                            Email = "student161@example.com",
                            Id = 161,
                            Name = "Student 161"
                        },
                        new
                        {
                            RA = "RA000162",
                            CPF = "123456789162",
                            Email = "student162@example.com",
                            Id = 162,
                            Name = "Student 162"
                        },
                        new
                        {
                            RA = "RA000163",
                            CPF = "123456789163",
                            Email = "student163@example.com",
                            Id = 163,
                            Name = "Student 163"
                        },
                        new
                        {
                            RA = "RA000164",
                            CPF = "123456789164",
                            Email = "student164@example.com",
                            Id = 164,
                            Name = "Student 164"
                        },
                        new
                        {
                            RA = "RA000165",
                            CPF = "123456789165",
                            Email = "student165@example.com",
                            Id = 165,
                            Name = "Student 165"
                        },
                        new
                        {
                            RA = "RA000166",
                            CPF = "123456789166",
                            Email = "student166@example.com",
                            Id = 166,
                            Name = "Student 166"
                        },
                        new
                        {
                            RA = "RA000167",
                            CPF = "123456789167",
                            Email = "student167@example.com",
                            Id = 167,
                            Name = "Student 167"
                        },
                        new
                        {
                            RA = "RA000168",
                            CPF = "123456789168",
                            Email = "student168@example.com",
                            Id = 168,
                            Name = "Student 168"
                        },
                        new
                        {
                            RA = "RA000169",
                            CPF = "123456789169",
                            Email = "student169@example.com",
                            Id = 169,
                            Name = "Student 169"
                        },
                        new
                        {
                            RA = "RA000170",
                            CPF = "123456789170",
                            Email = "student170@example.com",
                            Id = 170,
                            Name = "Student 170"
                        },
                        new
                        {
                            RA = "RA000171",
                            CPF = "123456789171",
                            Email = "student171@example.com",
                            Id = 171,
                            Name = "Student 171"
                        },
                        new
                        {
                            RA = "RA000172",
                            CPF = "123456789172",
                            Email = "student172@example.com",
                            Id = 172,
                            Name = "Student 172"
                        },
                        new
                        {
                            RA = "RA000173",
                            CPF = "123456789173",
                            Email = "student173@example.com",
                            Id = 173,
                            Name = "Student 173"
                        },
                        new
                        {
                            RA = "RA000174",
                            CPF = "123456789174",
                            Email = "student174@example.com",
                            Id = 174,
                            Name = "Student 174"
                        },
                        new
                        {
                            RA = "RA000175",
                            CPF = "123456789175",
                            Email = "student175@example.com",
                            Id = 175,
                            Name = "Student 175"
                        },
                        new
                        {
                            RA = "RA000176",
                            CPF = "123456789176",
                            Email = "student176@example.com",
                            Id = 176,
                            Name = "Student 176"
                        },
                        new
                        {
                            RA = "RA000177",
                            CPF = "123456789177",
                            Email = "student177@example.com",
                            Id = 177,
                            Name = "Student 177"
                        },
                        new
                        {
                            RA = "RA000178",
                            CPF = "123456789178",
                            Email = "student178@example.com",
                            Id = 178,
                            Name = "Student 178"
                        },
                        new
                        {
                            RA = "RA000179",
                            CPF = "123456789179",
                            Email = "student179@example.com",
                            Id = 179,
                            Name = "Student 179"
                        },
                        new
                        {
                            RA = "RA000180",
                            CPF = "123456789180",
                            Email = "student180@example.com",
                            Id = 180,
                            Name = "Student 180"
                        },
                        new
                        {
                            RA = "RA000181",
                            CPF = "123456789181",
                            Email = "student181@example.com",
                            Id = 181,
                            Name = "Student 181"
                        },
                        new
                        {
                            RA = "RA000182",
                            CPF = "123456789182",
                            Email = "student182@example.com",
                            Id = 182,
                            Name = "Student 182"
                        },
                        new
                        {
                            RA = "RA000183",
                            CPF = "123456789183",
                            Email = "student183@example.com",
                            Id = 183,
                            Name = "Student 183"
                        },
                        new
                        {
                            RA = "RA000184",
                            CPF = "123456789184",
                            Email = "student184@example.com",
                            Id = 184,
                            Name = "Student 184"
                        },
                        new
                        {
                            RA = "RA000185",
                            CPF = "123456789185",
                            Email = "student185@example.com",
                            Id = 185,
                            Name = "Student 185"
                        },
                        new
                        {
                            RA = "RA000186",
                            CPF = "123456789186",
                            Email = "student186@example.com",
                            Id = 186,
                            Name = "Student 186"
                        },
                        new
                        {
                            RA = "RA000187",
                            CPF = "123456789187",
                            Email = "student187@example.com",
                            Id = 187,
                            Name = "Student 187"
                        },
                        new
                        {
                            RA = "RA000188",
                            CPF = "123456789188",
                            Email = "student188@example.com",
                            Id = 188,
                            Name = "Student 188"
                        },
                        new
                        {
                            RA = "RA000189",
                            CPF = "123456789189",
                            Email = "student189@example.com",
                            Id = 189,
                            Name = "Student 189"
                        },
                        new
                        {
                            RA = "RA000190",
                            CPF = "123456789190",
                            Email = "student190@example.com",
                            Id = 190,
                            Name = "Student 190"
                        },
                        new
                        {
                            RA = "RA000191",
                            CPF = "123456789191",
                            Email = "student191@example.com",
                            Id = 191,
                            Name = "Student 191"
                        },
                        new
                        {
                            RA = "RA000192",
                            CPF = "123456789192",
                            Email = "student192@example.com",
                            Id = 192,
                            Name = "Student 192"
                        },
                        new
                        {
                            RA = "RA000193",
                            CPF = "123456789193",
                            Email = "student193@example.com",
                            Id = 193,
                            Name = "Student 193"
                        },
                        new
                        {
                            RA = "RA000194",
                            CPF = "123456789194",
                            Email = "student194@example.com",
                            Id = 194,
                            Name = "Student 194"
                        },
                        new
                        {
                            RA = "RA000195",
                            CPF = "123456789195",
                            Email = "student195@example.com",
                            Id = 195,
                            Name = "Student 195"
                        },
                        new
                        {
                            RA = "RA000196",
                            CPF = "123456789196",
                            Email = "student196@example.com",
                            Id = 196,
                            Name = "Student 196"
                        },
                        new
                        {
                            RA = "RA000197",
                            CPF = "123456789197",
                            Email = "student197@example.com",
                            Id = 197,
                            Name = "Student 197"
                        },
                        new
                        {
                            RA = "RA000198",
                            CPF = "123456789198",
                            Email = "student198@example.com",
                            Id = 198,
                            Name = "Student 198"
                        },
                        new
                        {
                            RA = "RA000199",
                            CPF = "123456789199",
                            Email = "student199@example.com",
                            Id = 199,
                            Name = "Student 199"
                        },
                        new
                        {
                            RA = "RA000200",
                            CPF = "123456789200",
                            Email = "student200@example.com",
                            Id = 200,
                            Name = "Student 200"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
